version: '2.1'
volumes:
  mongodb:
services:
  vueapp:
    image: 'vueapp:latest'
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    entrypoint: ../bin/docker_entrypoint.sh mongodb:27017
    restart: always
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "3334:3334"
    env_file:
      - .env
  mongodb:
    image: 'bitnami/mongodb:latest'
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - "mongodb:/bitnami"
